name: Build

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Build
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    defaults:
      run:
        working-directory: 24w14a-1.21.1-fabric/

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build
        env:
          GITHUB_PKG_R_TOKEN: ${{ secrets.PKG_R_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: 24w14a-1.21.1-fabric/build/libs/*.jar
        if: github.ref_type == 'tag'
